//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PM01_519_Yarakov
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moderator
    {
        public int ID { get; set; }
        public string FIO { get; set; }
        public int GenderID { get; set; }
        public string Email { get; set; }
        public System.DateTime Birthday { get; set; }
        public int CountryID { get; set; }
        public string Phone { get; set; }
        public int JobID { get; set; }
        public int EventID { get; set; }
        public string Password { get; set; }
        public string Photo { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Events Events { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Jobs Jobs { get; set; }
    }
}
